title: Nate's Dumb Blog
description: "A place for my unhinged thoughts"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: ncasados@live.com
github_username: marth141
twitter_username: cmdr_kero
# instagram_username: instagram
linkedin_username: ncasados
# facebook_username: facebook

# External API
giscus_repo: "marth141/marth141.github.io"
giscus_repoId: "R_kgDOLfkAgA"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOLfkAgM4Cd7p7"
goatcounter_code:
google_analytics:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
